import it.fpagano.pattern_recognition.model.LineFunction;
import it.fpagano.pattern_recognition.model.Point;

import javax.sound.sampled.Line;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static void main(String[] args) {
        LineFunction l = LineFunction.of(new Point(1,1), new Point(2,2)).get();

        LineFunction l2 = LineFunction.of(new Point(3,3), new Point(4,4)).get();

        System.out.println(l.equals(l2));
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
