import it.fpagano.pattern_recognition.model.Point;
import it.fpagano.pattern_recognition.model.Space;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static void main(String[] args) {
        Space s = new Space();

        s.addPoint(new Point(1,1));
        s.addPoint(new Point(1,2));

        s.addPoint(new Point(2,1));
        s.addPoint(new Point(2,2));

        s.addPoint(new Point(3,1));
        s.addPoint(new Point(3,2));


        System.out.println(s.getLines(3));

    }

    public boolean someLibraryMethod() {
        return true;
    }
}
